const fs = require('fs');
const path = require('path');

const root = process.cwd();
const prerequisite = path.join(
  root,
  'apps/api/src/modules/settlements/settlement-recovery-audit.service.ts',
);

if (!fs.existsSync(prerequisite)) {
  throw new Error(
    'Sprint 7.6.6 não encontrada. Aplique e valide a 7.6.6 antes da 7.6.7.',
  );
}

const payload = {"apps/api/src/modules/settlements/settlement-readiness.service.ts": "aW1wb3J0IHsgSW5qZWN0YWJsZSB9IGZyb20gJ0BuZXN0anMvY29tbW9uJzsKaW1wb3J0IHsKICBTZWxsZXJTZXR0bGVtZW50U3RhdHVzLAogIFNldHRsZW1lbnRCYXRjaFN0YXR1cywKfSBmcm9tICdAcHJpc21hL2NsaWVudCc7CgppbXBvcnQgeyBQcmlzbWFTZXJ2aWNlIH0gZnJvbSAnLi4vcHJpc21hL3ByaXNtYS5zZXJ2aWNlJzsKCkBJbmplY3RhYmxlKCkKZXhwb3J0IGNsYXNzIFNldHRsZW1lbnRSZWFkaW5lc3NTZXJ2aWNlIHsKICBjb25zdHJ1Y3Rvcihwcml2YXRlIHJlYWRvbmx5IHByaXNtYTogUHJpc21hU2VydmljZSkge30KCiAgYXN5bmMgc3RhdHVzKCkgewogICAgY29uc3Qgbm93ID0gbmV3IERhdGUoKTsKICAgIGNvbnN0IHBheW91dFBlbmRpbmdDdXRvZmYgPSBuZXcgRGF0ZSgKICAgICAgbm93LmdldFRpbWUoKSAtIDMwICogNjAgKiAxMDAwLAogICAgKTsKICAgIGNvbnN0IHJlYWR5Q3V0b2ZmID0gbmV3IERhdGUoCiAgICAgIG5vdy5nZXRUaW1lKCkgLSA2MCAqIDYwICogMTAwMCwKICAgICk7CgogICAgY29uc3QgWwogICAgICBkYkhlYWx0aHksCiAgICAgIHN0dWNrUGF5b3V0UGVuZGluZywKICAgICAgc3RhbGVSZWFkeSwKICAgICAgZmFpbGVkU2V0dGxlbWVudHMsCiAgICAgIG9wZW5CYXRjaGVzLAogICAgXSA9IGF3YWl0IFByb21pc2UuYWxsKFsKICAgICAgdGhpcy5kYXRhYmFzZUhlYWx0aHkoKSwKICAgICAgdGhpcy5wcmlzbWEuc2VsbGVyU2V0dGxlbWVudC5jb3VudCh7CiAgICAgICAgd2hlcmU6IHsKICAgICAgICAgIHN0YXR1czogU2VsbGVyU2V0dGxlbWVudFN0YXR1cy5QQVlPVVRfUEVORElORywKICAgICAgICAgIHBheW91dFJlcXVlc3RlZEF0OiB7IGx0OiBwYXlvdXRQZW5kaW5nQ3V0b2ZmIH0sCiAgICAgICAgfSwKICAgICAgfSksCiAgICAgIHRoaXMucHJpc21hLnNlbGxlclNldHRsZW1lbnQuY291bnQoewogICAgICAgIHdoZXJlOiB7CiAgICAgICAgICBzdGF0dXM6IFNlbGxlclNldHRsZW1lbnRTdGF0dXMuUkVBRFksCiAgICAgICAgICB1cGRhdGVkQXQ6IHsgbHQ6IHJlYWR5Q3V0b2ZmIH0sCiAgICAgICAgfSwKICAgICAgfSksCiAgICAgIHRoaXMucHJpc21hLnNlbGxlclNldHRsZW1lbnQuY291bnQoewogICAgICAgIHdoZXJlOiB7CiAgICAgICAgICBzdGF0dXM6IFNlbGxlclNldHRsZW1lbnRTdGF0dXMuRkFJTEVELAogICAgICAgIH0sCiAgICAgIH0pLAogICAgICB0aGlzLnByaXNtYS5zZXR0bGVtZW50QmF0Y2guY291bnQoewogICAgICAgIHdoZXJlOiB7CiAgICAgICAgICBzdGF0dXM6IFNldHRsZW1lbnRCYXRjaFN0YXR1cy5PUEVOLAogICAgICAgIH0sCiAgICAgIH0pLAogICAgXSk7CgogICAgY29uc3QgcmVhc29uczogc3RyaW5nW10gPSBbXTsKCiAgICBpZiAoIWRiSGVhbHRoeSkgcmVhc29ucy5wdXNoKCdEQVRBQkFTRV9VTkFWQUlMQUJMRScpOwogICAgaWYgKHN0dWNrUGF5b3V0UGVuZGluZyA+IDApIHsKICAgICAgcmVhc29ucy5wdXNoKCdTVFVDS19QQVlPVVRfUEVORElORycpOwogICAgfQoKICAgIHJldHVybiB7CiAgICAgIHJlYWR5OiByZWFzb25zLmxlbmd0aCA9PT0gMCwKICAgICAgY2hlY2tlZEF0OiBub3csCiAgICAgIHJlYXNvbnMsCiAgICAgIHRocmVzaG9sZHM6IHsKICAgICAgICBwYXlvdXRQZW5kaW5nTWludXRlczogMzAsCiAgICAgICAgc3RhbGVSZWFkeU1pbnV0ZXM6IDYwLAogICAgICB9LAogICAgICBjb3VudGVyczogewogICAgICAgIHN0dWNrUGF5b3V0UGVuZGluZywKICAgICAgICBzdGFsZVJlYWR5LAogICAgICAgIGZhaWxlZFNldHRsZW1lbnRzLAogICAgICAgIG9wZW5CYXRjaGVzLAogICAgICB9LAogICAgfTsKICB9CgogIHByaXZhdGUgYXN5bmMgZGF0YWJhc2VIZWFsdGh5KCkgewogICAgdHJ5IHsKICAgICAgYXdhaXQgdGhpcy5wcmlzbWEuJHF1ZXJ5UmF3YFNFTEVDVCAxYDsKICAgICAgcmV0dXJuIHRydWU7CiAgICB9IGNhdGNoIHsKICAgICAgcmV0dXJuIGZhbHNlOwogICAgfQogIH0KfQo=", "apps/api/src/modules/settlements/settlement-metrics.service.ts": "aW1wb3J0IHsgSW5qZWN0YWJsZSB9IGZyb20gJ0BuZXN0anMvY29tbW9uJzsKaW1wb3J0IHsKICBTZWxsZXJTZXR0bGVtZW50U3RhdHVzLAogIFNldHRsZW1lbnRCYXRjaFN0YXR1cywKfSBmcm9tICdAcHJpc21hL2NsaWVudCc7CgppbXBvcnQgeyBQcmlzbWFTZXJ2aWNlIH0gZnJvbSAnLi4vcHJpc21hL3ByaXNtYS5zZXJ2aWNlJzsKCkBJbmplY3RhYmxlKCkKZXhwb3J0IGNsYXNzIFNldHRsZW1lbnRNZXRyaWNzU2VydmljZSB7CiAgY29uc3RydWN0b3IocHJpdmF0ZSByZWFkb25seSBwcmlzbWE6IFByaXNtYVNlcnZpY2UpIHt9CgogIGFzeW5jIHNuYXBzaG90KCkgewogICAgY29uc3Qgbm93ID0gbmV3IERhdGUoKTsKICAgIGNvbnN0IHN0dWNrQ3V0b2ZmID0gbmV3IERhdGUoCiAgICAgIG5vdy5nZXRUaW1lKCkgLSAzMCAqIDYwICogMTAwMCwKICAgICk7CgogICAgY29uc3QgW3NldHRsZW1lbnRSb3dzLCBiYXRjaFJvd3MsIHN0dWNrXSA9CiAgICAgIGF3YWl0IFByb21pc2UuYWxsKFsKICAgICAgICB0aGlzLnByaXNtYS5zZWxsZXJTZXR0bGVtZW50Lmdyb3VwQnkoewogICAgICAgICAgYnk6IFsnc3RhdHVzJ10sCiAgICAgICAgICBfY291bnQ6IHsgX2FsbDogdHJ1ZSB9LAogICAgICAgIH0pLAogICAgICAgIHRoaXMucHJpc21hLnNldHRsZW1lbnRCYXRjaC5ncm91cEJ5KHsKICAgICAgICAgIGJ5OiBbJ3N0YXR1cyddLAogICAgICAgICAgX2NvdW50OiB7IF9hbGw6IHRydWUgfSwKICAgICAgICB9KSwKICAgICAgICB0aGlzLnByaXNtYS5zZWxsZXJTZXR0bGVtZW50LmNvdW50KHsKICAgICAgICAgIHdoZXJlOiB7CiAgICAgICAgICAgIHN0YXR1czogU2VsbGVyU2V0dGxlbWVudFN0YXR1cy5QQVlPVVRfUEVORElORywKICAgICAgICAgICAgcGF5b3V0UmVxdWVzdGVkQXQ6IHsgbHQ6IHN0dWNrQ3V0b2ZmIH0sCiAgICAgICAgICB9LAogICAgICAgIH0pLAogICAgICBdKTsKCiAgICBjb25zdCBzZXR0bGVtZW50cyA9IE9iamVjdC52YWx1ZXMoCiAgICAgIFNlbGxlclNldHRsZW1lbnRTdGF0dXMsCiAgICApLnJlZHVjZTxSZWNvcmQ8c3RyaW5nLCBudW1iZXI+PigoYWNjLCBzdGF0dXMpID0+IHsKICAgICAgYWNjW3N0YXR1c10gPSAwOwogICAgICByZXR1cm4gYWNjOwogICAgfSwge30pOwoKICAgIGZvciAoY29uc3Qgcm93IG9mIHNldHRsZW1lbnRSb3dzKSB7CiAgICAgIHNldHRsZW1lbnRzW3Jvdy5zdGF0dXNdID0gcm93Ll9jb3VudC5fYWxsOwogICAgfQoKICAgIGNvbnN0IGJhdGNoZXMgPSBPYmplY3QudmFsdWVzKAogICAgICBTZXR0bGVtZW50QmF0Y2hTdGF0dXMsCiAgICApLnJlZHVjZTxSZWNvcmQ8c3RyaW5nLCBudW1iZXI+PigoYWNjLCBzdGF0dXMpID0+IHsKICAgICAgYWNjW3N0YXR1c10gPSAwOwogICAgICByZXR1cm4gYWNjOwogICAgfSwge30pOwoKICAgIGZvciAoY29uc3Qgcm93IG9mIGJhdGNoUm93cykgewogICAgICBiYXRjaGVzW3Jvdy5zdGF0dXNdID0gcm93Ll9jb3VudC5fYWxsOwogICAgfQoKICAgIHJldHVybiB7CiAgICAgIGdlbmVyYXRlZEF0OiBub3csCiAgICAgIHNldHRsZW1lbnRzLAogICAgICBiYXRjaGVzLAogICAgICBhbGVydHM6IHsKICAgICAgICBzdHVja1BheW91dFBlbmRpbmc6IHN0dWNrLAogICAgICAgIGZhaWxlZFNldHRsZW1lbnRzOgogICAgICAgICAgc2V0dGxlbWVudHNbU2VsbGVyU2V0dGxlbWVudFN0YXR1cy5GQUlMRURdID8/IDAsCiAgICAgIH0sCiAgICB9OwogIH0KfQo=", "apps/api/src/modules/settlements/settlement-operational-monitor.service.ts": "aW1wb3J0IHsgSW5qZWN0YWJsZSwgTG9nZ2VyIH0gZnJvbSAnQG5lc3Rqcy9jb21tb24nOwppbXBvcnQgeyBTZWxsZXJTZXR0bGVtZW50U3RhdHVzIH0gZnJvbSAnQHByaXNtYS9jbGllbnQnOwoKaW1wb3J0IHsgUHJpc21hU2VydmljZSB9IGZyb20gJy4uL3ByaXNtYS9wcmlzbWEuc2VydmljZSc7CgpleHBvcnQgdHlwZSBTZXR0bGVtZW50T3BlcmF0aW9uYWxBbGVydCA9IHsKICBjb2RlOgogICAgfCAnU1RVQ0tfUEFZT1VUX1BFTkRJTkcnCiAgICB8ICdGQUlMRURfU0VUVExFTUVOVFMnCiAgICB8ICdTVEFMRV9SRUFEWV9TRVRUTEVNRU5UUyc7CiAgc2V2ZXJpdHk6ICdXQVJOSU5HJyB8ICdDUklUSUNBTCc7CiAgY291bnQ6IG51bWJlcjsKICBtZXNzYWdlOiBzdHJpbmc7Cn07CgpASW5qZWN0YWJsZSgpCmV4cG9ydCBjbGFzcyBTZXR0bGVtZW50T3BlcmF0aW9uYWxNb25pdG9yU2VydmljZSB7CiAgcHJpdmF0ZSByZWFkb25seSBsb2dnZXIgPSBuZXcgTG9nZ2VyKAogICAgU2V0dGxlbWVudE9wZXJhdGlvbmFsTW9uaXRvclNlcnZpY2UubmFtZSwKICApOwoKICBjb25zdHJ1Y3Rvcihwcml2YXRlIHJlYWRvbmx5IHByaXNtYTogUHJpc21hU2VydmljZSkge30KCiAgYXN5bmMgc2NhbigpOiBQcm9taXNlPHsKICAgIHNjYW5uZWRBdDogRGF0ZTsKICAgIGFsZXJ0czogU2V0dGxlbWVudE9wZXJhdGlvbmFsQWxlcnRbXTsKICB9PiB7CiAgICBjb25zdCBub3cgPSBuZXcgRGF0ZSgpOwogICAgY29uc3QgcGVuZGluZ0N1dG9mZiA9IG5ldyBEYXRlKAogICAgICBub3cuZ2V0VGltZSgpIC0gMzAgKiA2MCAqIDEwMDAsCiAgICApOwogICAgY29uc3QgcmVhZHlDdXRvZmYgPSBuZXcgRGF0ZSgKICAgICAgbm93LmdldFRpbWUoKSAtIDYwICogNjAgKiAxMDAwLAogICAgKTsKCiAgICBjb25zdCBbc3R1Y2tQZW5kaW5nLCBmYWlsZWQsIHN0YWxlUmVhZHldID0KICAgICAgYXdhaXQgUHJvbWlzZS5hbGwoWwogICAgICAgIHRoaXMucHJpc21hLnNlbGxlclNldHRsZW1lbnQuY291bnQoewogICAgICAgICAgd2hlcmU6IHsKICAgICAgICAgICAgc3RhdHVzOgogICAgICAgICAgICAgIFNlbGxlclNldHRsZW1lbnRTdGF0dXMuUEFZT1VUX1BFTkRJTkcsCiAgICAgICAgICAgIHBheW91dFJlcXVlc3RlZEF0OiB7IGx0OiBwZW5kaW5nQ3V0b2ZmIH0sCiAgICAgICAgICB9LAogICAgICAgIH0pLAogICAgICAgIHRoaXMucHJpc21hLnNlbGxlclNldHRsZW1lbnQuY291bnQoewogICAgICAgICAgd2hlcmU6IHsKICAgICAgICAgICAgc3RhdHVzOiBTZWxsZXJTZXR0bGVtZW50U3RhdHVzLkZBSUxFRCwKICAgICAgICAgIH0sCiAgICAgICAgfSksCiAgICAgICAgdGhpcy5wcmlzbWEuc2VsbGVyU2V0dGxlbWVudC5jb3VudCh7CiAgICAgICAgICB3aGVyZTogewogICAgICAgICAgICBzdGF0dXM6IFNlbGxlclNldHRsZW1lbnRTdGF0dXMuUkVBRFksCiAgICAgICAgICAgIHVwZGF0ZWRBdDogeyBsdDogcmVhZHlDdXRvZmYgfSwKICAgICAgICAgIH0sCiAgICAgICAgfSksCiAgICAgIF0pOwoKICAgIGNvbnN0IGFsZXJ0czogU2V0dGxlbWVudE9wZXJhdGlvbmFsQWxlcnRbXSA9IFtdOwoKICAgIGlmIChzdHVja1BlbmRpbmcgPiAwKSB7CiAgICAgIGFsZXJ0cy5wdXNoKHsKICAgICAgICBjb2RlOiAnU1RVQ0tfUEFZT1VUX1BFTkRJTkcnLAogICAgICAgIHNldmVyaXR5OiAnQ1JJVElDQUwnLAogICAgICAgIGNvdW50OiBzdHVja1BlbmRpbmcsCiAgICAgICAgbWVzc2FnZToKICAgICAgICAgICdIw6Egc2V0dGxlbWVudHMgUEFZT1VUX1BFTkRJTkcgYWNpbWEgZGUgMzAgbWludXRvcy4nLAogICAgICB9KTsKICAgIH0KCiAgICBpZiAoZmFpbGVkID4gMCkgewogICAgICBhbGVydHMucHVzaCh7CiAgICAgICAgY29kZTogJ0ZBSUxFRF9TRVRUTEVNRU5UUycsCiAgICAgICAgc2V2ZXJpdHk6ICdDUklUSUNBTCcsCiAgICAgICAgY291bnQ6IGZhaWxlZCwKICAgICAgICBtZXNzYWdlOgogICAgICAgICAgJ0jDoSBzZXR0bGVtZW50cyBGQUlMRUQgYWd1YXJkYW5kbyBhbsOhbGlzZS9yZWNvdmVyeS4nLAogICAgICB9KTsKICAgIH0KCiAgICBpZiAoc3RhbGVSZWFkeSA+IDApIHsKICAgICAgYWxlcnRzLnB1c2goewogICAgICAgIGNvZGU6ICdTVEFMRV9SRUFEWV9TRVRUTEVNRU5UUycsCiAgICAgICAgc2V2ZXJpdHk6ICdXQVJOSU5HJywKICAgICAgICBjb3VudDogc3RhbGVSZWFkeSwKICAgICAgICBtZXNzYWdlOgogICAgICAgICAgJ0jDoSBzZXR0bGVtZW50cyBSRUFEWSBzZW0gc29saWNpdGHDp8OjbyBkZSBwYXlvdXQgaMOhIG1haXMgZGUgNjAgbWludXRvcy4nLAogICAgICB9KTsKICAgIH0KCiAgICBmb3IgKGNvbnN0IGFsZXJ0IG9mIGFsZXJ0cykgewogICAgICBjb25zdCBsaW5lID0gYFske2FsZXJ0LmNvZGV9XSAke2FsZXJ0Lm1lc3NhZ2V9IGNvdW50PSR7YWxlcnQuY291bnR9YDsKICAgICAgaWYgKGFsZXJ0LnNldmVyaXR5ID09PSAnQ1JJVElDQUwnKSB7CiAgICAgICAgdGhpcy5sb2dnZXIuZXJyb3IobGluZSk7CiAgICAgIH0gZWxzZSB7CiAgICAgICAgdGhpcy5sb2dnZXIud2FybihsaW5lKTsKICAgICAgfQogICAgfQoKICAgIHJldHVybiB7IHNjYW5uZWRBdDogbm93LCBhbGVydHMgfTsKICB9Cn0K", "apps/api/src/modules/settlements/settlement-readiness.service.spec.ts": "aW1wb3J0IHsgU2V0dGxlbWVudFJlYWRpbmVzc1NlcnZpY2UgfSBmcm9tICcuL3NldHRsZW1lbnQtcmVhZGluZXNzLnNlcnZpY2UnOwoKZGVzY3JpYmUoJ1NldHRsZW1lbnRSZWFkaW5lc3NTZXJ2aWNlIC0gU3ByaW50IDcuNi43JywgKCkgPT4gewogIGZ1bmN0aW9uIGJ1aWxkKCkgewogICAgY29uc3QgcHJpc21hOiBhbnkgPSB7CiAgICAgICRxdWVyeVJhdzogamVzdC5mbigpLm1vY2tSZXNvbHZlZFZhbHVlKFt7ICc/Y29sdW1uPyc6IDEgfV0pLAogICAgICBzZWxsZXJTZXR0bGVtZW50OiB7CiAgICAgICAgY291bnQ6IGplc3QuZm4oKSwKICAgICAgfSwKICAgICAgc2V0dGxlbWVudEJhdGNoOiB7CiAgICAgICAgY291bnQ6IGplc3QuZm4oKSwKICAgICAgfSwKICAgIH07CgogICAgcmV0dXJuIHsKICAgICAgcHJpc21hLAogICAgICBzZXJ2aWNlOiBuZXcgU2V0dGxlbWVudFJlYWRpbmVzc1NlcnZpY2UocHJpc21hKSwKICAgIH07CiAgfQoKICBpdCgnZmljYSByZWFkeSBxdWFuZG8gYmFuY28gZSBzZXR0bGVtZW50cyBlc3TDo28gc2F1ZMOhdmVpcycsIGFzeW5jICgpID0+IHsKICAgIGNvbnN0IHsgcHJpc21hLCBzZXJ2aWNlIH0gPSBidWlsZCgpOwoKICAgIHByaXNtYS5zZWxsZXJTZXR0bGVtZW50LmNvdW50CiAgICAgIC5tb2NrUmVzb2x2ZWRWYWx1ZU9uY2UoMCkKICAgICAgLm1vY2tSZXNvbHZlZFZhbHVlT25jZSgwKQogICAgICAubW9ja1Jlc29sdmVkVmFsdWVPbmNlKDApOwogICAgcHJpc21hLnNldHRsZW1lbnRCYXRjaC5jb3VudC5tb2NrUmVzb2x2ZWRWYWx1ZSgxKTsKCiAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzZXJ2aWNlLnN0YXR1cygpOwoKICAgIGV4cGVjdChyZXN1bHQucmVhZHkpLnRvQmUodHJ1ZSk7CiAgICBleHBlY3QocmVzdWx0LnJlYXNvbnMpLnRvRXF1YWwoW10pOwogIH0pOwoKICBpdCgnZmljYSBub3QtcmVhZHkgcXVhbmRvIGjDoSBQQVlPVVRfUEVORElORyBwcmVzbycsIGFzeW5jICgpID0+IHsKICAgIGNvbnN0IHsgcHJpc21hLCBzZXJ2aWNlIH0gPSBidWlsZCgpOwoKICAgIHByaXNtYS5zZWxsZXJTZXR0bGVtZW50LmNvdW50CiAgICAgIC5tb2NrUmVzb2x2ZWRWYWx1ZU9uY2UoMikKICAgICAgLm1vY2tSZXNvbHZlZFZhbHVlT25jZSgwKQogICAgICAubW9ja1Jlc29sdmVkVmFsdWVPbmNlKDApOwogICAgcHJpc21hLnNldHRsZW1lbnRCYXRjaC5jb3VudC5tb2NrUmVzb2x2ZWRWYWx1ZSgwKTsKCiAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzZXJ2aWNlLnN0YXR1cygpOwoKICAgIGV4cGVjdChyZXN1bHQucmVhZHkpLnRvQmUoZmFsc2UpOwogICAgZXhwZWN0KHJlc3VsdC5yZWFzb25zKS50b0NvbnRhaW4oCiAgICAgICdTVFVDS19QQVlPVVRfUEVORElORycsCiAgICApOwogICAgZXhwZWN0KHJlc3VsdC5jb3VudGVycy5zdHVja1BheW91dFBlbmRpbmcpLnRvQmUoMik7CiAgfSk7CgogIGl0KCdmaWNhIG5vdC1yZWFkeSBxdWFuZG8gUG9zdGdyZVNRTCBuw6NvIHJlc3BvbmRlJywgYXN5bmMgKCkgPT4gewogICAgY29uc3QgeyBwcmlzbWEsIHNlcnZpY2UgfSA9IGJ1aWxkKCk7CgogICAgcHJpc21hLiRxdWVyeVJhdy5tb2NrUmVqZWN0ZWRWYWx1ZSgKICAgICAgbmV3IEVycm9yKCdwb3N0Z3JlcyB1bmF2YWlsYWJsZScpLAogICAgKTsKICAgIHByaXNtYS5zZWxsZXJTZXR0bGVtZW50LmNvdW50Lm1vY2tSZXNvbHZlZFZhbHVlKDApOwogICAgcHJpc21hLnNldHRsZW1lbnRCYXRjaC5jb3VudC5tb2NrUmVzb2x2ZWRWYWx1ZSgwKTsKCiAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzZXJ2aWNlLnN0YXR1cygpOwoKICAgIGV4cGVjdChyZXN1bHQucmVhZHkpLnRvQmUoZmFsc2UpOwogICAgZXhwZWN0KHJlc3VsdC5yZWFzb25zKS50b0NvbnRhaW4oCiAgICAgICdEQVRBQkFTRV9VTkFWQUlMQUJMRScsCiAgICApOwogIH0pOwp9KTsK", "apps/api/src/modules/settlements/settlement-metrics.service.spec.ts": "aW1wb3J0IHsKICBTZWxsZXJTZXR0bGVtZW50U3RhdHVzLAogIFNldHRsZW1lbnRCYXRjaFN0YXR1cywKfSBmcm9tICdAcHJpc21hL2NsaWVudCc7CgppbXBvcnQgeyBTZXR0bGVtZW50TWV0cmljc1NlcnZpY2UgfSBmcm9tICcuL3NldHRsZW1lbnQtbWV0cmljcy5zZXJ2aWNlJzsKCmRlc2NyaWJlKCdTZXR0bGVtZW50TWV0cmljc1NlcnZpY2UgLSBTcHJpbnQgNy42LjcnLCAoKSA9PiB7CiAgaXQoJ2FncmVnYSBzZXR0bGVtZW50cywgYmF0Y2hlcyBlIGFsZXJ0YXMgb3BlcmFjaW9uYWlzJywgYXN5bmMgKCkgPT4gewogICAgY29uc3QgcHJpc21hOiBhbnkgPSB7CiAgICAgIHNlbGxlclNldHRsZW1lbnQ6IHsKICAgICAgICBncm91cEJ5OiBqZXN0LmZuKCkubW9ja1Jlc29sdmVkVmFsdWUoWwogICAgICAgICAgewogICAgICAgICAgICBzdGF0dXM6IFNlbGxlclNldHRsZW1lbnRTdGF0dXMuU0VUVExFRCwKICAgICAgICAgICAgX2NvdW50OiB7IF9hbGw6IDcgfSwKICAgICAgICAgIH0sCiAgICAgICAgICB7CiAgICAgICAgICAgIHN0YXR1czogU2VsbGVyU2V0dGxlbWVudFN0YXR1cy5GQUlMRUQsCiAgICAgICAgICAgIF9jb3VudDogeyBfYWxsOiAyIH0sCiAgICAgICAgICB9LAogICAgICAgIF0pLAogICAgICAgIGNvdW50OiBqZXN0LmZuKCkubW9ja1Jlc29sdmVkVmFsdWUoMSksCiAgICAgIH0sCiAgICAgIHNldHRsZW1lbnRCYXRjaDogewogICAgICAgIGdyb3VwQnk6IGplc3QuZm4oKS5tb2NrUmVzb2x2ZWRWYWx1ZShbCiAgICAgICAgICB7CiAgICAgICAgICAgIHN0YXR1czogU2V0dGxlbWVudEJhdGNoU3RhdHVzLk9QRU4sCiAgICAgICAgICAgIF9jb3VudDogeyBfYWxsOiAzIH0sCiAgICAgICAgICB9LAogICAgICAgIF0pLAogICAgICB9LAogICAgfTsKCiAgICBjb25zdCBzZXJ2aWNlID0gbmV3IFNldHRsZW1lbnRNZXRyaWNzU2VydmljZShwcmlzbWEpOwogICAgY29uc3QgcmVzdWx0ID0gYXdhaXQgc2VydmljZS5zbmFwc2hvdCgpOwoKICAgIGV4cGVjdCgKICAgICAgcmVzdWx0LnNldHRsZW1lbnRzWwogICAgICAgIFNlbGxlclNldHRsZW1lbnRTdGF0dXMuU0VUVExFRAogICAgICBdLAogICAgKS50b0JlKDcpOwogICAgZXhwZWN0KAogICAgICByZXN1bHQuc2V0dGxlbWVudHNbCiAgICAgICAgU2VsbGVyU2V0dGxlbWVudFN0YXR1cy5GQUlMRUQKICAgICAgXSwKICAgICkudG9CZSgyKTsKICAgIGV4cGVjdCgKICAgICAgcmVzdWx0LmJhdGNoZXNbU2V0dGxlbWVudEJhdGNoU3RhdHVzLk9QRU5dLAogICAgKS50b0JlKDMpOwogICAgZXhwZWN0KHJlc3VsdC5hbGVydHMuc3R1Y2tQYXlvdXRQZW5kaW5nKS50b0JlKDEpOwogICAgZXhwZWN0KHJlc3VsdC5hbGVydHMuZmFpbGVkU2V0dGxlbWVudHMpLnRvQmUoMik7CiAgfSk7Cn0pOwo=", "apps/api/src/modules/settlements/settlement-operational-monitor.service.spec.ts": "aW1wb3J0IHsgU2V0dGxlbWVudE9wZXJhdGlvbmFsTW9uaXRvclNlcnZpY2UgfSBmcm9tICcuL3NldHRsZW1lbnQtb3BlcmF0aW9uYWwtbW9uaXRvci5zZXJ2aWNlJzsKCmRlc2NyaWJlKCdTZXR0bGVtZW50T3BlcmF0aW9uYWxNb25pdG9yU2VydmljZSAtIFNwcmludCA3LjYuNycsICgpID0+IHsKICBpdCgnZ2VyYSBhbGVydGFzIHBhcmEgc3R1Y2ssIGZhaWxlZCBlIHN0YWxlIHJlYWR5JywgYXN5bmMgKCkgPT4gewogICAgY29uc3QgcHJpc21hOiBhbnkgPSB7CiAgICAgIHNlbGxlclNldHRsZW1lbnQ6IHsKICAgICAgICBjb3VudDogamVzdAogICAgICAgICAgLmZuKCkKICAgICAgICAgIC5tb2NrUmVzb2x2ZWRWYWx1ZU9uY2UoMikKICAgICAgICAgIC5tb2NrUmVzb2x2ZWRWYWx1ZU9uY2UoMSkKICAgICAgICAgIC5tb2NrUmVzb2x2ZWRWYWx1ZU9uY2UoMyksCiAgICAgIH0sCiAgICB9OwoKICAgIGNvbnN0IHNlcnZpY2UgPQogICAgICBuZXcgU2V0dGxlbWVudE9wZXJhdGlvbmFsTW9uaXRvclNlcnZpY2UocHJpc21hKTsKCiAgICBjb25zdCByZXN1bHQgPSBhd2FpdCBzZXJ2aWNlLnNjYW4oKTsKCiAgICBleHBlY3QocmVzdWx0LmFsZXJ0cykudG9IYXZlTGVuZ3RoKDMpOwogICAgZXhwZWN0KHJlc3VsdC5hbGVydHMubWFwKCh4KSA9PiB4LmNvZGUpKS50b0VxdWFsKAogICAgICBleHBlY3QuYXJyYXlDb250YWluaW5nKFsKICAgICAgICAnU1RVQ0tfUEFZT1VUX1BFTkRJTkcnLAogICAgICAgICdGQUlMRURfU0VUVExFTUVOVFMnLAogICAgICAgICdTVEFMRV9SRUFEWV9TRVRUTEVNRU5UUycsCiAgICAgIF0pLAogICAgKTsKICB9KTsKCiAgaXQoJ27Do28gZ2VyYSBhbGVydGEgcXVhbmRvIG9wZXJhw6fDo28gZXN0w6Egc2F1ZMOhdmVsJywgYXN5bmMgKCkgPT4gewogICAgY29uc3QgcHJpc21hOiBhbnkgPSB7CiAgICAgIHNlbGxlclNldHRsZW1lbnQ6IHsKICAgICAgICBjb3VudDogamVzdC5mbigpLm1vY2tSZXNvbHZlZFZhbHVlKDApLAogICAgICB9LAogICAgfTsKCiAgICBjb25zdCBzZXJ2aWNlID0KICAgICAgbmV3IFNldHRsZW1lbnRPcGVyYXRpb25hbE1vbml0b3JTZXJ2aWNlKHByaXNtYSk7CgogICAgY29uc3QgcmVzdWx0ID0gYXdhaXQgc2VydmljZS5zY2FuKCk7CgogICAgZXhwZWN0KHJlc3VsdC5hbGVydHMpLnRvRXF1YWwoW10pOwogIH0pOwp9KTsK"};

for (const [rel, b64] of Object.entries(payload)) {
  const file = path.join(root, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, Buffer.from(b64, 'base64'));
  console.log('[Sprint 7.6.7]', rel);
}

const moduleFile = path.join(
  root,
  'apps/api/src/modules/settlements/settlements.module.ts',
);

let mod = fs.readFileSync(moduleFile, 'utf8');

const imports = [
  "import { SettlementMetricsService } from './settlement-metrics.service';",
  "import { SettlementOperationalMonitorService } from './settlement-operational-monitor.service';",
  "import { SettlementReadinessService } from './settlement-readiness.service';",
];

for (const line of imports) {
  if (!mod.includes(line)) {
    const anchor =
      "import { SettlementRecoveryAuditService } from './settlement-recovery-audit.service';";
    mod = mod.replace(anchor, anchor + '\n' + line);
  }
}

if (!mod.includes('    SettlementReadinessService,')) {
  mod = mod.replace(
    '    SettlementRecoveryAuditService,',
    '    SettlementRecoveryAuditService,\n    SettlementReadinessService,\n    SettlementMetricsService,\n    SettlementOperationalMonitorService,',
  );
}

fs.writeFileSync(moduleFile, mod);
console.log('[Sprint 7.6.7]', 'apps/api/src/modules/settlements/settlements.module.ts');

const controllerFile = path.join(
  root,
  'apps/api/src/modules/settlements/settlements.controller.ts',
);

let controller = fs.readFileSync(controllerFile, 'utf8');

const controllerImports = [
  "import { SettlementMetricsService } from './settlement-metrics.service';",
  "import { SettlementOperationalMonitorService } from './settlement-operational-monitor.service';",
  "import { SettlementReadinessService } from './settlement-readiness.service';",
];

for (const line of controllerImports) {
  if (!controller.includes(line)) {
    const anchor =
      "import { SettlementRecoveryAuditService } from './settlement-recovery-audit.service';";
    controller = controller.replace(anchor, anchor + '\n' + line);
  }
}

if (!controller.includes('private readonly readiness: SettlementReadinessService')) {
  controller = controller.replace(
    '    private readonly recoveryAudit: SettlementRecoveryAuditService,',
    '    private readonly recoveryAudit: SettlementRecoveryAuditService,\n' +
    '    private readonly readiness: SettlementReadinessService,\n' +
    '    private readonly metrics: SettlementMetricsService,\n' +
    '    private readonly operationalMonitor: SettlementOperationalMonitorService,',
  );
}

const marker = '  private context(';
if (!controller.includes("@Get('operations/readiness')")) {
  const endpoints = `  @Get('operations/readiness')
  readinessStatus() {
    return this.readiness.status();
  }

  @Get('operations/metrics')
  metricsSnapshot() {
    return this.metrics.snapshot();
  }

  @Post('operations/scan')
  operationalScan() {
    return this.operationalMonitor.scan();
  }

`;
  controller = controller.replace(marker, endpoints + marker);
}

fs.writeFileSync(controllerFile, controller);
console.log('[Sprint 7.6.7]', 'apps/api/src/modules/settlements/settlements.controller.ts');

console.log('[Sprint 7.6.7] aplicação concluída.');
console.log('[Sprint 7.6.7] Nenhuma migration necessária.');
console.log('[Sprint 7.6.7] Adicionados readiness, métricas e alertas operacionais de Settlement.');
